### ISSUE TITLE
Links to example configuration lead to private repository

### ISSUE THREAD

**Issue by alexkops** [cyfrania/logback-slack-appender#1]
When I click on the links for the example logback xml files in the readme, I get a 404 not found. Likely because the repository is private.
E.g. https://github.com/cyfrania/logback-slack-appender-examples/blob/main/example-webhook/src/main/resources/logback.xml

**Comment by maximro** [comment]
Hi @alexkops 
Thanks for reporting the issue.
The [logback-slack-appender-examples](https://github.com/cyfrania/logback-slack-appender-examples) is now public and the link to the example configuration should work.
